### ISSUE TITLE
better align wing boxes

### ISSUE THREAD

**Issue by cmnord** [cory2067/next-house#10]
They look very awkward rn

![image](https://user-images.githubusercontent.com/14882297/29303477-2e7547fe-815b-11e7-8439-915456cc1de7.png)

![image](https://user-images.githubusercontent.com/14882297/29303488-3e6ed9a4-815b-11e7-93db-6f0ad3a72427.png)

**Comment by cory2067** [comment]
alignment has gotten worse since this

**Comment by cory2067** [comment]
basically fixed in in 74381b88bf00bd413076df1dc607d246436ea273
