### ISSUE TITLE
Make pages responsive

### ISSUE THREAD

**Issue by jynnie** [cory2067/next-house#2]
obvious on home page with the by the numbers part as well as slideshow

**Comment by cmnord** [comment]
@MFarejowicz

**Comment by cmnord** [comment]
navbar is responsive now yay #12

**Comment by cmnord** [comment]
consider changing `_includes/wings.html` to flexboxes instead of rows/cols

**Comment by cory2067** [comment]
From b2daa03, the general layout of the site is now deliciously responsive. There are still some details though that need improved responsiveness.

So closing this and going to open separate issues for those details.
