### ISSUE TITLE
Animate.css not working on deployment

### ISSUE THREAD

**Issue by longnguyen1997** [cory2067/next-house#20]
When using `bundle exec jekyll serve`, the `localhost` copy of the site has full support for `animate.css`, but upon deployment, the site hosted has no animations. I'm not sure exactly what the issue is and why it's happening.

**Comment by cmnord** [comment]
I can look into this

**Comment by cory2067** [comment]
Seems to me like this works when actually deployed on `next.mit.edu`.
Can somebody confirm so we can close this?

**Comment by cmnord** [comment]
Works for me!

**Comment by cmnord** [comment]
Both on mobile and web
